swagger: "2.0"
info:
  description: "Warehouse API"
  version: "1.0.0"
  title: "Simple Warehouse data"
host: "localhost:8080"
basePath: "/v1"
tags:
  - name: "warehouse"
    description: "warehouse"
schemes:
  - http
paths:
  /datasource:
    get:
      tags:
        - "warehouse"
      summary: "Get available datasource"
      operationId: "getAvailableDatasource"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Dimensions"
  /analytics:
    get:
      tags:
        - "warehouse"
      summary: "Get available analytics"
      operationId: "getAnalytics"
      produces:
        - "application/json"
      parameters:
        - name: metrics
          in: query
          description:  Set of metrics (plus calculated ones) to be aggregated on
          required: true
          type: array
          items:
            type: string
            enum:
              - clicks
              - impressions
            default: clicks
          collectionFormat: multi
        - name: dimensions
          in: query
          description: an optional set of dimensions to be grouped by
          type: string
          enum:
            - campaign
            - datasource
        - name: dateFrom
          in: query
          description: date from
          type: string
          format: date
        - name: dateTo
          in: query
          description: date from
          format: date
          type: string
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Analytics"
  /analytics/dimentions:
    get:
      tags:
        - "warehouse"
      summary: "Find datasource or campaign which meets metrics criteria"
      operationId: "getAnalyticDimensions"
      produces:
        - "application/json"
      parameters:
        - name: metrics
          in: query
          description:  Set of metrics (plus calculated ones) to be aggregated on
          required: true
          type: string
          enum:
            - clicks
            - impressions
            - ctr
          default: clicks
        - name: dimensions
          required: true
          in: query
          description: an optional set of dimensions to be grouped by
          type: string
          enum:
            - campaign
            - datasource
          default: campaign
        - name: valueFrom
          in: query
          description: date from
          type: number
        - name: valueTo
          in: query
          description: date from
          type: number
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Dimensions"
definitions:
  Dimensions:
    required:
      - id
      - name
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
  Analytics:
    type: "object"
    properties:
      totalClicks:
        type: "integer"
      totalImpressions:
        type: "integer"
      clickThroughRate:
        type: "number"
      dimension:
        type: "string"
      dimensionName:
        type: "string"
      dateFrom:
        type: "string"
      dateTo:
        type: "string"
