swagger: "2.0"
info:
  description: "Warehouse API"
  version: "1.0.0"
  title: "Simple Warehouse data"
host: "localhost:8080"
basePath: "/v1"
tags:
  - name: "warehouse"
    description: "warehouse"
schemes:
  - http
paths:
  /datasources:
    get:
      tags:
        - "warehouse"
      summary: "Get available datasources"
      operationId: "getAvailableDatasource"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Dimension"
  /analytics:
    get:
      tags:
        - "warehouse"
      summary: "Find available analytics and filter by params"
      operationId: "findAnalyticsByParam"
      produces:
        - "application/json"
      parameters:
        - name: metrics
          in: query
          description:  Set of metrics (plus calculated ones) to be aggregated on
          required: true
          type: array
          items:
            type: string
            enum:
              - clicks
              - impressions
            default: clicks
          collectionFormat: multi
        - name: dimensions
          in: query
          description: an optional set of dimensions to be grouped by
          type: string
          enum:
            - campaign
            - datasource
        - name: dateFrom
          in: query
          description: date from
          type: string
          format: date
        - name: dateTo
          in: query
          description: date from
          format: date
          type: string
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Analytic"
  /analytics/campaign/top:
    get:
      tags:
        - "warehouse"
      summary: "Find top campaign and sort by param"
      operationId: "findTopCampaignBy"
      produces:
        - "application/json"
      parameters:
        - name: sortBy
          in: query
          description:  Sorting param clicks, impressions, ctr
          required: true
          type: string
          enum:
            - clicks
            - impressions
            - ctr
          default: clicks
        - name: dateFrom
          in: query
          description: date from
          type: string
          format: date
        - name: dateTo
          in: query
          description: date from
          format: date
          type: string
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Analytic"
definitions:
  Dimension:
    required:
      - id
      - name
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
  Analytic:
    type: "object"
    properties:
      totalClicks:
        type: "integer"
      totalImpressions:
        type: "integer"
      clickThroughRate:
        type: "number"
      dimensionName:
        type: "string"
