spring:
  datamongodb.database: warehouse
  jackson:
    serialization.write_dates_as_timestamps: false
    default-property-inclusion: non_null
server:
  shutdown: graceful
logging:
  level.org.springframework.web: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: mappings